// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJLsFAw06xe0F6u8IXziBggB8yGhLIIo',
    appId: '1:460127483137:web:72eeb842784c9b17ec9700',
    messagingSenderId: '460127483137',
    projectId: 'limaenaccion-edda7',
    authDomain: 'limaenaccion-edda7.firebaseapp.com',
    storageBucket: 'limaenaccion-edda7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-rJEBnDJxDiLaE2E-xLBUYcqliy0npY',
    appId: '1:460127483137:android:3f0ea21668f6a6cbec9700',
    messagingSenderId: '460127483137',
    projectId: 'limaenaccion-edda7',
    storageBucket: 'limaenaccion-edda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvW0yCkmNcpbeREbtMtzxv3TGf146Xmi0',
    appId: '1:460127483137:ios:4ad0094a7cd3df95ec9700',
    messagingSenderId: '460127483137',
    projectId: 'limaenaccion-edda7',
    storageBucket: 'limaenaccion-edda7.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionMovil',
  );
}
